alias ls='ls -GFv'      
alias ll='ls -l'                          
alias la='ls -A'                                                                                    
alias gitlog='git log --graph  --abbrev-commit --parents --all --date-order --decorate --pretty=oneline'
alias tree='tree -FCN'
